from youtube_transcript_api import YouTubeTranscriptApi


TRANSCRIPT_FILES_LOCATION = "files/transcripts_from_yt/"


def save_transcript_to_file(text, filename):
    with open(TRANSCRIPT_FILES_LOCATION + filename, "w", encoding='utf-8') as file:
        file.write(str(text))


def transcript_from_yt_video(video_id):
    text = ''
    # retrieve the available transcripts
    transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
    # iterate over all available transcripts
    for transcript in transcript_list:
        text = transcript.translate('ru').fetch()

        # the Transcript object provides metadata properties
        # print(
        #     transcript.video_id,
        #     transcript.language,
        #     transcript.language_code,
        #     # whether it has been manually created or generated by YouTube
        #     transcript.is_generated,
        #     # whether this transcript can be translated or not
        #     transcript.is_translatable,
        #     # a list of languages the transcript can be translated to
        #     transcript.translation_languages,
        # )
        # fetch the actual transcript data
        # print(transcript.fetch())
        # translating the transcript will return another transcript object
    # # you can also directly filter for the language you are looking for, using the transcript list
    # transcript = transcript_list.find_transcript(['de', 'en'])
    #
    # # or just filter for manually created transcripts
    # transcript = transcript_list.find_manually_created_transcript(['de', 'en'])
    #
    # # or automatically generated ones
    # transcript = transcript_list.find_generated_transcript(['ru'])

    transcript = ''
    for phrase in text:
        transcript += phrase["text"] + ' '
    transcript = transcript.lower().strip()

    save_transcript_to_file(transcript, video_id + '.txt')
    return transcript


if __name__ == "__main__":
    print(transcript_from_yt_video("XK6v8L_4Oj0"))
